class Quote {
    constructor(text, author){
        this.text = text;
        this.author = author;
    }
}

const quotes = [
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    new Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    new Quote("The best way to predict the future is to create it.", "Peter Drucker"),
    new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    new Quote("The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", "Helen Keller"),
    new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    new Quote("The secret of getting ahead is getting started.", "Mark Twain"),
    new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"),
    new Quote("Life isn’t about finding yourself. It’s about creating yourself.", "George Bernard Shaw"),
    new Quote("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
    new Quote("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
    new Quote("The best revenge is massive success.", "Frank Sinatra"),
    new Quote("Challenges are what make life interesting. Overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    new Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    new Quote("The best way to predict the future is to create it.", "Peter Drucker"),
    new Quote("Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"),
    new Quote("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    new Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    new Quote("What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", "Helen Keller"),
    new Quote("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    new Quote("If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do, you have to keep moving forward.", "Martin Luther King Jr."),
    new Quote("The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", "Jordan Belfort"),
    new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"),
    new Quote("Life isn’t about finding yourself. It’s about creating yourself.", "George Bernard Shaw"),
    new Quote("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
    new Quote("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
    new Quote("The best revenge is massive success.", "Frank Sinatra"),
    new Quote("Challenges are what make life interesting. Overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    new Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    new Quote("The best way to predict the future is to create it.", "Peter Drucker"),
    new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    new Quote("The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", "Helen Keller"),
    new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    new Quote("The secret of getting ahead is getting started.", "Mark Twain"),
    new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"),
    new Quote("Life isn’t about finding yourself. It’s about creating yourself.", "George Bernard Shaw"),
    new Quote("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
    new Quote("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
    new Quote("The best revenge is massive success.", "Frank Sinatra"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    new Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    new Quote("The best way to predict the future is to create it.", "Peter Drucker"),
    new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    new Quote("The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", "Helen Keller"),
    new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    new Quote("The secret of getting ahead is getting started.", "Mark Twain"),
    new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"),
    new Quote("Life isn’t about finding yourself. It’s about creating yourself.", "George Bernard Shaw"),
    new Quote("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
    new Quote("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
    new Quote("The best revenge is massive success.", "Frank Sinatra"),
    new Quote("Challenges are what make life interesting. Overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"),
    new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    new Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    new Quote("The best way to predict the future is to create it.", "Peter Drucker"),
    new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    new Quote("The best and most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", "Helen Keller"),
    new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    new Quote("The secret of getting ahead is getting started.", "Mark Twain"),
    new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
    new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"),
    new Quote("Life isn’t about finding yourself. It’s about creating yourself.", "George Bernard Shaw"),
    new Quote("Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"),
    new Quote("The best preparation for tomorrow is doing your best today.", "H. Jackson Brown Jr."),
    new Quote("The best revenge is massive success.", "Frank Sinatra"),
    new Quote("Challenges are what make life interesting. Overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    new Quote("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "Jimmy Dean"),
    new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    new Quote("The only way to do great work is to love what you do.", "Steve Jobs"),
    new Quote("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    new Quote("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    new Quote("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    new Quote("Life is a flower of which love is the honey.", "Victor Hugo"),
    new Quote("You only live once, but if you do it right, once is enough.", "Mae West"),
    new Quote("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
    new Quote("In the end, it's not the years in your life that count, it's the life in your years.", "Abraham Lincoln"),
    new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    new Quote("Challenges are what make life interesting. Overcoming them is what makes life meaningful.", "Joshua J. Marine"),
];

function getRandomQuote(){
    if (quotes.length === 0) {
        document.getElementById("quote-text").textContent = "No quotes available.";
        document.getElementById("quote-author").textContent = "";
        return;
    }
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const textElement = document.getElementById("quote-text");
    const authorElement = document.getElementById("quote-author");

    textElement.textContent = quotes[randomIndex].text;
    authorElement.textContent = "- " + quotes[randomIndex].author;
  }